# Arquivo: .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "frontend"
      - "dependencies"

  - package-ecosystem: "maven"
    directory: "/api/api" 
    schedule:
      interval: "weekly"
    labels:
      - "backend"
      - "java"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"