spring.application.name=api
server.port=${SERVER_PORT:8080}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/estuda_mais_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
api.security.token.secret=${JWT_SECRET:32323232323232323232323232323232323232323232323232323232323232323232323232323232323}

# Logging
logging.level.root=INFO
logging.level.com.estuda_mais=DEBUG

# CORS Configuration (if needed)
spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=*
spring.web.cors.allowed-headers=*
