name: CI Fullstack

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6 # Atualizado para v4 (mais estável)

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run frontend tests
        run: npm run test

  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: 'maven'

      - name: Build backend
        # Ajustado para a pasta onde está o pom.xml
        working-directory: ./api/api
        run: mvn clean install